#!/usr/bin/env python3
"""Record explicit, reproducible hashes for protected processed-corpus scopes."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
from typing import Iterable


OUTPUT_JSON = "data/derived/protected-hash-scopes.json"
OUTPUT_MARKDOWN = "docs/protected-hash-scope-audit.md"
BASELINE_REVISION = "59bde5a"
CURRENT_REVISION = "HEAD"
ALGORITHM = "sha256(path_utf8 + NUL + raw_file_sha256_digest)"


def tracked_paths(root: Path, prefixes: Iterable[str], revision: str | None = None) -> list[str]:
    if revision is None:
        result = subprocess.run(
            ["git", "ls-files", "--", *prefixes],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )
        return sorted(line for line in result.stdout.splitlines() if line)
    result = subprocess.run(
        ["git", "ls-tree", "-r", "--name-only", revision, "--", *prefixes],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    return sorted(line for line in result.stdout.splitlines() if line)


def file_bytes(root: Path, path: str, revision: str | None = None) -> bytes:
    if revision is None:
        return (root / path).read_bytes()
    result = subprocess.run(
        ["git", "show", f"{revision}:{path}"],
        cwd=root,
        check=True,
        capture_output=True,
    )
    return result.stdout


def aggregate(root: Path, paths: list[str], revision: str | None = None) -> str:
    digest = hashlib.sha256()
    for path in paths:
        content_digest = hashlib.sha256(file_bytes(root, path, revision)).digest()
        digest.update(path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(content_digest)
    return digest.hexdigest()


def scope(root: Path, name: str, prefixes: list[str], *, revision: str | None = None) -> dict[str, object]:
    paths = tracked_paths(root, prefixes, revision)
    return {
        "name": name,
        "roots": prefixes,
        "revision": revision or "working-tree",
        "file_count": len(paths),
        "algorithm": ALGORITHM,
        "sha256": aggregate(root, paths, revision),
    }


def build(root: Path) -> dict[str, object]:
    processed_roots = ["content/processed/shishuo", "content/processed/jinshu"]
    current = scope(root, "canonical-processed-shishuo-jinshu", processed_roots)
    head = scope(root, "canonical-processed-shishuo-jinshu-at-head", processed_roots, revision=CURRENT_REVISION)
    baseline = scope(
        root,
        "historical-wp1-baseline-processed-shishuo-jinshu",
        processed_roots,
        revision=BASELINE_REVISION,
    )
    shishuo = scope(root, "canonical-processed-shishuo", ["content/processed/shishuo"])
    jinshu = scope(root, "canonical-processed-jinshu", ["content/processed/jinshu"])
    baseline_shishuo = scope(
        root,
        "historical-wp1-baseline-processed-shishuo",
        ["content/processed/shishuo"],
        revision=BASELINE_REVISION,
    )
    baseline_jinshu = scope(
        root,
        "historical-wp1-baseline-processed-jinshu",
        ["content/processed/jinshu"],
        revision=BASELINE_REVISION,
    )
    document = {
        "schema": 1,
        "algorithm": ALGORITHM,
        "baseline_revision": BASELINE_REVISION,
        "current_revision_reference": CURRENT_REVISION,
        "scopes": [
            current,
            head,
            baseline,
            shishuo,
            jinshu,
            baseline_shishuo,
            baseline_jinshu,
        ],
        "comparisons": {
            "working_tree_equals_head_same_scope": current["sha256"] == head["sha256"]
            and current["file_count"] == head["file_count"],
            "shishuo_unchanged_since_baseline": shishuo["sha256"] == baseline_shishuo["sha256"]
            and shishuo["file_count"] == baseline_shishuo["file_count"],
            "processed_scope_changed_only_by_jinshu_completion": shishuo["sha256"] == baseline_shishuo["sha256"]
            and shishuo["file_count"] == baseline_shishuo["file_count"]
            and jinshu["file_count"] != baseline_jinshu["file_count"],
        },
    }
    (root / OUTPUT_JSON).parent.mkdir(parents=True, exist_ok=True)
    (root / OUTPUT_JSON).write_text(
        json.dumps(document, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    scopes = {item["name"]: item for item in document["scopes"]}
    comparisons = document["comparisons"]
    lines = [
        "# Protected Processed-Corpus Hash Scope Audit",
        "",
        "This report is generated by `scripts/audit_protected_hash_scopes.py`. It names the file set and aggregation algorithm instead of using the ambiguous label `protected corpus hash`.",
        "",
        f"- algorithm: `{ALGORITHM}`",
        f"- historical comparison revision: `{BASELINE_REVISION}`",
        "",
        "| scope | revision | files | SHA-256 |",
        "|---|---|---:|---|",
    ]
    for item in document["scopes"]:
        lines.append(
            f"| `{item['name']}` | `{item['revision']}` | {item['file_count']} | `{item['sha256']}` |"
        )
    lines.extend(
        [
            "",
            "## Explanation",
            "",
            f"The earlier WP1 protected-scope count is reproducibly the `{BASELINE_REVISION}` tree: it contains {scopes['historical-wp1-baseline-processed-shishuo-jinshu']['file_count']} processed files ({scopes['historical-wp1-baseline-processed-shishuo']['file_count']} Shishuo and {scopes['historical-wp1-baseline-processed-jinshu']['file_count']} Jinshu). At that point Jinshu was still the partial 34-file corpus.",
            f"The current CRL1 scope contains {scopes['canonical-processed-shishuo-jinshu']['file_count']} processed files ({scopes['canonical-processed-shishuo']['file_count']} Shishuo and {scopes['canonical-processed-jinshu']['file_count']} complete Jinshu files). The Shishuo scope is unchanged from the historical baseline; the aggregate differs because the processed Jinshu corpus was later completed.",
            f"Working tree and `{CURRENT_REVISION}` have the same {scopes['canonical-processed-shishuo-jinshu']['file_count']}-file scope and hash: `{comparisons['working_tree_equals_head_same_scope']}`. No protected processed-corpus content changed in this CRL1.1 task.",
            "The historical report’s exact old hash is not stored as a tracked report artifact, but its file count and scope are recoverable from the repository revision above. The two scopes must not be compared as if they were one invariant.",
        ]
    )
    (root / OUTPUT_MARKDOWN).parent.mkdir(parents=True, exist_ok=True)
    (root / OUTPUT_MARKDOWN).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return document


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    print(json.dumps(build(args.root.resolve()), ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
